### ISSUE TITLE
Crawl all stickers on the entire site?

### ISSUE THREAD

**Issue by chaoscreater** [QaziSajid/LINE-sticker-downloader#1]
Is it possible to download all stickers on the entire site in one go?

**Comment by complex31** [comment]
I have no idea why you would want to do that. There are so much more crap stickers than good ones.
But, you could write a loop to run from 1 to 10^7, which should give you all possible sticker codes. You can simply pass those numbers as argument to ``sd.dwnl`` inside the ``linkgen.py`` file. If sticker exists for that code it will be downloaded. But be careful of the storage space its going to take.
